"use client";

import { CheckCircle2 } from "lucide-react";
import PulseLogo from "@/src/components/PulseLogo";
import PulsePhoneShowcase from "@/src/components/PulsePhoneShowcase";
import ProfileForm from "@/src/components/ProfileForm";
import ProtectedRoute from "@/src/components/ProtectedRoute";

function SetupContent({ user }) {
  return (
    <div className="pulse-page min-h-screen text-white">
      <main className="relative mx-auto grid min-h-screen max-w-7xl gap-6 px-4 py-8 sm:px-6 lg:grid-cols-[0.78fr_1.22fr] lg:px-8">
        <section className="pulse-panel flex flex-col justify-between rounded-[1.75rem] p-6">
          <div>
            <PulseLogo />
            <p className="pulse-kicker mt-10">
              Profile setup
            </p>
            <h1 className="mt-4 text-4xl font-black leading-tight tracking-[-0.03em] text-white sm:text-5xl">
              Your first plan starts with your profile.
            </h1>
            <p className="mt-5 text-sm leading-7 text-[var(--fc-muted)]">
              After saving, the app will create your workout plan, nutrition targets,
              and first progress entry in Supabase.
            </p>
          </div>
          <div className="mt-8 grid gap-3 text-sm text-white">
            {[
              "Workout plan generated by goal + level + days/week.",
              "Nutrition plan calculated from body profile and goal.",
              "All personal data filtered by authenticated user.",
            ].map((item) => (
              <div key={item} className="flex gap-3 rounded-2xl border border-[var(--fc-border)] bg-black/24 p-4">
                <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[var(--fc-accent)]" />
                <span>{item}</span>
              </div>
            ))}
          </div>
          <div className="hidden lg:block">
            <PulsePhoneShowcase compact />
          </div>
        </section>

        <section className="pulse-panel rounded-[1.75rem] p-5 sm:p-6">
          <ProfileForm
            user={user}
            setup
            submitLabel="Create profile and plans"
            onSaved={() => {
              window.setTimeout(() => window.location.replace("/dashboard"), 700);
            }}
          />
        </section>
      </main>
    </div>
  );
}

export default function ProfileSetupPage() {
  return (
    <ProtectedRoute requireProfile={false} redirectIfProfile>
      {({ user }) => <SetupContent user={user} />}
    </ProtectedRoute>
  );
}
